---
version: '3.9'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.8.68.0/22

services:
  # === Bot 1: Market_Making ===
  freqtrade_mm:
    image: freqtradeorg/freqtrade:2025.7
    build:
      context: .
      dockerfile: "./Dockerfile.technical"
    restart: unless-stopped
    container_name: MM_ave
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./scripts:/freqtrade/scripts"
      - "./HL_data_collector:/freqtrade/HL_data_collector"
    ports:
      - "127.0.0.1:3004:8080"   # API for bot #1
    environment:
      - HL_DATA_LOC=/freqtrade/HL_data_collector/HL_data/
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_mm.log
      --db-url sqlite:////freqtrade/user_data/tradesv3_mm.sqlite
      --config /freqtrade/user_data/config.json
      --strategy avellaneda

  # === HL Data Collector ===
  hl-collector:
    build:
      context: ./HL_data_collector
      dockerfile: Dockerfile
    container_name: hl-collector
    environment:
      # Comma-separated symbols; defaults match your script
      SYMBOLS: ${SYMBOLS:-BTC,ETH,SOL,WLFI}
      OUTPUT_DIR: ${OUTPUT_DIR:-HL_data}
      ORDERBOOK_DEPTH: ${ORDERBOOK_DEPTH:-20}
      TZ: ${TZ:-UTC}
    volumes:
      # Persist data on the host; aligns with OUTPUT_DIR default
      - ./HL_data_collector/HL_data:/app/HL_data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["python", "run_collector.py"]

  # # === Bot 2: Market_Making_SHORT (new) ===
  # freqtrade_mm_short:
  #   image: freqtradeorg/freqtrade:2025.7
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.technical"
  #   restart: unless-stopped
  #   container_name: MM_ADV_short
  #   volumes:
  #     - "./user_data:/freqtrade/user_data"
  #     - "./scripts:/freqtrade/scripts"
  #   ports:
  #     - "127.0.0.1:3005:8081"   # API for bot #2 (different host port and container)
  #   command: >
  #     trade
  #     --logfile /freqtrade/user_data/logs/freqtrade_mm_short.log
  #     --db-url sqlite:////freqtrade/user_data/tradesv3_mm_short.sqlite
  #     --config /freqtrade/user_data/config_short.json
  #     --strategy Market_Making_short
